module_birthday = "Birthday"

mt_birthday_overview = "birthdays"
md_birthday_overview = "Overview of birthday"
birthday = "Birthday"
email_me_birthdays = "Email me weekly birthdays"
announce_my_birthday = "Show my birthday"
birthday_position = "Birthday link position"
birthday_count = "%d birthdays"
birthday_mail_subject = "Birthdays this week"
birthday_mail_body = "Birthdays during the coming week: %s"
page_position_off = "Off"
page_position_title = "Title bar"
page_position_top = "Top bar"
page_position_left = "Left bar"
page_position_right = "Right bar"
page_position_bottom = "Bottom bar"
